name: easy_pay
description: "Paga Fácil"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  google_fonts: ^6.3.0
  go_router: ^16.1.0
  firebase_core: ^4.0.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  firebase_auth: ^6.0.0
  get_it: ^8.2.0
  cloud_firestore: ^6.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

